const colors = {
  light: {
    text: "#FFFFFF",
    tint: "#CC2486",
    background: "#0E0E0E",
    foreground: "#FFFFFF",
    card: "#1A1A1A",
    cardForeground: "#FFFFFF",
    primary: "#CC2486",
    primaryForeground: "#FFFFFF",
    secondary: "#1A1A1A",
    secondaryForeground: "#FFFFFF",
    muted: "#242424",
    mutedForeground: "#A0A0A0",
    accent: "#8D1FF4",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2E2E2E",
    input: "#1A1A1A",
    surface: "#1A1A1A",
    surfaceElevated: "#242424",
    tabBar: "#111111",
    pink: "#CC2486",
    purple: "#8D1FF4",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#CC2486",
    background: "#0E0E0E",
    foreground: "#FFFFFF",
    card: "#1A1A1A",
    cardForeground: "#FFFFFF",
    primary: "#CC2486",
    primaryForeground: "#FFFFFF",
    secondary: "#1A1A1A",
    secondaryForeground: "#FFFFFF",
    muted: "#242424",
    mutedForeground: "#A0A0A0",
    accent: "#8D1FF4",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2E2E2E",
    input: "#1A1A1A",
    surface: "#1A1A1A",
    surfaceElevated: "#242424",
    tabBar: "#111111",
    pink: "#CC2486",
    purple: "#8D1FF4",
  },
  radius: 10,
};

export default colors;
