-- =============================================================================
-- DAG TAXONOMY: Seed genre_taxonomy_exclude (drop list)
-- Run after genre_taxonomy_schema.sql. Idempotent.
-- =============================================================================

-- Drop list: normalized_key values to exclude from taxonomy (from genres table + path heuristics)
INSERT INTO genre_taxonomy_exclude (normalized_key) VALUES
(' consistency'), (' edit'), ('consistency'), ('edit'), ('"foreign agent" in russia'), ('00s'), ('1 hit wonder'), ('10s'), ('1960s'), ('1980s'), ('1990s'), ('2005'), ('2008 universal fire victim'), ('2010s'), ('2016'), ('2020s'), ('3 stars'), ('5 stars'), ('60s'), ('70s'), ('80s'), ('90s'), ('<3'), ('[1]'), ('[2]'), ('[3]'), ('[4]'), ('[5]'), ('academy award winner'), ('across the universe'), ('acting'), ('actor'), ('actors'), ('actress'), ('actresses'), ('adventure'), ('all'), ('alternative singer/songwriter'), ('amazing'), ('amazing voice'), ('animator'), ('ass'), ('belgian singer'), ('broiche pop'), ('columbus'), ('cordio dio'), ('country singer'), ('eurovision 2023 artists'), ('eurovision 2024 artists'), ('exceptional voice'), ('female artists'), ('female singer'), ('femalesinger'), ('fictitious artist'), ('fiji'), ('fmera artist'), ('fuzzy artist series'), ('german voice actor'), ('guinea bissau'), ('italian singer songwriter'), ('kill your own'), ('killyourown'), ('lesser known yet streamable artists'), ('liberia'), ('liberian'), ('motion picture actors and actresses'), ('münchen'), ('munchen'), ('multiple artists'), ('nekromantik'), ('oregon'), ('phleng phuea chiwit'), ('portland oregon usa'), ('pudel artists'), ('rock artist'), ('salento'), ('series title as artist'), ('singer'), ('singer singwriter'), ('singer songwriter'), ('singer songwriters'), ('singer/songwriter'), ('singersong writer'), ('small artist'), ('special purpose artist'), ('the masked singer'), ('two or more artists with the same name'), ('use actual artists'), ('valencia'), ('valencian'), ('various artists are a pita on lastfm'), ('venezuela'), ('venezuelan'), ('voice actor'), ('wolfs of the masked singer'), ('yanni')
ON CONFLICT (normalized_key) DO NOTHING;
